export const Resources = {
    CommandClickToOpen: "&#8984;+Click to follow link",
    CtrlClickToOpen: "CTRL+Click to follow link",
    NoSuggestionsFound: "No suggestions found",
    OK: "OK",
    Cancel: "Cancel",
    Color_Black: "Black",
    Color_Blue: "Blue",
    Color_Cyan: "Cyan",
    Color_DarkBlue: "Dark Blue",
    Color_DarkerBlue: "Darker Blue",
    Color_DarkerGray: "Darker Gray",
    Color_DarkerGreen: "Darker Green",
    Color_DarkerOrange: "Darker Orange",
    Color_DarkerPurple: "Darker Purple",
    Color_DarkerRed: "Darker Red",
    Color_DarkerYellow: "Darker Yellow",
    Color_DarkGray: "Dark Gray",
    Color_DarkGreen: "Dark Green",
    Color_DarkOrange: "Dark Orange",
    Color_DarkPurple: "Dark Purple",
    Color_DarkRed: "Dark Red",
    Color_DarkYellow: "Dark Yellow",
    Color_Gray: "Gray",
    Color_Green: "Green",
    Color_LightBlue: "Light Blue",
    Color_LightCyan: "Light Cyan",
    Color_LightGray: "Light Gray",
    Color_LightGreen: "Light Green",
    Color_LightMagenta: "Light Magenta",
    Color_LightOrange: "Light Orange",
    Color_LightPurple: "Light Purple",
    Color_LightRed: "Light Red",
    Color_LightYellow: "Light Yellow",
    Color_Magenta: "Magenta",
    Color_Orange: "Orange",
    Color_Purple: "Purple",
    Color_Red: "Red",
    Color_White: "White",
    Color_Yellow: "Yellow",
    Toolbar_Bold: "Bold",
    Toolbar_BulletedList: "Bulleted list",
    Toolbar_ClearFormat: "Clear format",
    Toolbar_Emoji: "Insert emoji",
    Toolbar_FontColor: "Font color",
    Toolbar_Header: "Header",
    Toolbar_HeaderN: "Header {0}",
    Toolbar_Highlight: "Highlight",
    Toolbar_Indent: "Increase indent",
    Toolbar_InsertImage: "Insert image",
    Toolbar_Italic: "Italic",
    Toolbar_Link: "Create link",
    Toolbar_NumberedList: "Numbered list",
    Toolbar_Outdent: "Decrease indent",
    Toolbar_Strikethrough: "Strikethrough",
    Toolbar_Underline: "Underline",
    Toolbar_Unlink: "Remove link",
    Toolbar_Code: "Code",
    SearchForEmoji: "Search for emoji",
    FontColorPicker_AriaLabel: "Font color picker",
    HeaderMenu_AriaLabel: "Header menu",
    HighlightColorPicker_AriaLabel: "Highlight color picker",
    Toolbar_More: "More commands",
    InsertLink_FieldLabel: "Address"
};
